spring.application.name=Dyanamic-Quiz-Application

#gemini.api.key=AIzaSyCby0-LAUbKyDRS8yebX-ne75r7CcBLj1o
#gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent

# No URL needed! The SDK knows where to go.
spring.ai.google.genai.api-key=AIzaSyCby0-LAUbKyDRS8yebX-ne75r7CcBLj1o
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite
