spring.application.name=Dyanamic-Quiz-Application



## No URL needed! The SDK knows where to go.
#spring.ai.google.genai.api-key=${GEMINI_API_KEY}
#spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite



# Your Google Gemini API Key
gemini.api.key=_your_api_key


# Allow PDF uploads up to 50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
